/*
 * This file is generated by jOOQ.
 */
package maks.molch.dmitr.core.jooq;


import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import maks.molch.dmitr.core.jooq.tables.CarrierTable;
import maks.molch.dmitr.core.jooq.tables.PurchasedTicketsTable;
import maks.molch.dmitr.core.jooq.tables.RouteTable;
import maks.molch.dmitr.core.jooq.tables.TicketTable;
import maks.molch.dmitr.core.jooq.tables.TokenTable;
import maks.molch.dmitr.core.jooq.tables.UserTable;

import org.jetbrains.annotations.NotNull;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.10"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>CARRIER_TABLE</code>.
     */
    public final CarrierTable CARRIER_TABLE = CarrierTable.CARRIER_TABLE;

    /**
     * The table <code>PURCHASED_TICKETS_TABLE</code>.
     */
    public final PurchasedTicketsTable PURCHASED_TICKETS_TABLE = PurchasedTicketsTable.PURCHASED_TICKETS_TABLE;

    /**
     * The table <code>ROUTE_TABLE</code>.
     */
    public final RouteTable ROUTE_TABLE = RouteTable.ROUTE_TABLE;

    /**
     * The table <code>TICKET_TABLE</code>.
     */
    public final TicketTable TICKET_TABLE = TicketTable.TICKET_TABLE;

    /**
     * The table <code>TOKEN_TABLE</code>.
     */
    public final TokenTable TOKEN_TABLE = TokenTable.TOKEN_TABLE;

    /**
     * The table <code>USER_TABLE</code>.
     */
    public final UserTable USER_TABLE = UserTable.USER_TABLE;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    @NotNull
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    @NotNull
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            CarrierTable.CARRIER_TABLE,
            PurchasedTicketsTable.PURCHASED_TICKETS_TABLE,
            RouteTable.ROUTE_TABLE,
            TicketTable.TICKET_TABLE,
            TokenTable.TOKEN_TABLE,
            UserTable.USER_TABLE
        );
    }
}
