version: "3"

services:
  core:
    build:
      context: ./core
      dockerfile: Dockerfile
    image: core-service
    environment:
      POSTGRES_URL: jdbc:postgresql://postgresql:5432/core
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      JWT_PRIVATE_KEY: ${PRIV_KEY}
      JWT_PUBLIC_KEY: ${PUB_KEY}
    container_name: core-service
    ports:
      - "8080:8080"
    networks:
      - backend

  postgresql:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=core
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      - postgresql
    command:
      - --hub-mode=off
      - --changelog-file=changelog/master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/core
      - --username=postgres
      - --password=postgres
      - update
    volumes:
      - ./core/src/main/resources/db/migrations:/liquibase/changelog
    networks:
      - backend

volumes:
  database:

networks:
  backend:
    driver: bridge