version: "3"

services:
  core:
    build:
      context: ./core
      dockerfile: Dockerfile
    image: core-service
    environment:
      POSTGRES_URL: jdbc:postgresql://postgresql:5432/core
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      JWT_PRIVATE_KEY: ${PRIV_KEY}
      JWT_PUBLIC_KEY: ${PUB_KEY}
    container_name: core-service
    ports:
      - "8080:8080"
    networks:
      - backend

  postgresql:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=core
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"

  postgresql-analytics:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=analytics
    volumes:
      - database_analytics:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5433:5432"

  redis:
    image: redis:latest
    container_name: redis_container
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1


volumes:
  database:
  database_analytics:
  redis_data:

networks:
  backend:
    driver: bridge