/*
 * This file is generated by jOOQ.
 */
package maks.molch.dmitr.core.jooq.tables.records;


import jakarta.validation.constraints.Size;
import maks.molch.dmitr.core.jooq.tables.TicketTable;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.processing.Generated;
import java.beans.ConstructorProperties;
import java.math.BigInteger;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.10"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TicketTableRecord extends UpdatableRecordImpl<TicketTableRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>TICKET_TABLE.ID</code>.
     */
    public void setId(@Nullable Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>TICKET_TABLE.ID</code>.
     */
    @Nullable
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>TICKET_TABLE.ROUTE_ID</code>.
     */
    public void setRouteId(@NotNull Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>TICKET_TABLE.ROUTE_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Integer getRouteId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>TICKET_TABLE.DATE_AND_TIME</code>.
     */
    public void setDateAndTime(@NotNull LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>TICKET_TABLE.DATE_AND_TIME</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public LocalDateTime getDateAndTime() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>TICKET_TABLE.SEAT_NUMBER</code>.
     */
    public void setSeatNumber(@NotNull Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>TICKET_TABLE.SEAT_NUMBER</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Integer getSeatNumber() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>TICKET_TABLE.PRICE</code>.
     */
    public void setPrice(@NotNull BigInteger value) {
        set(4, value);
    }

    /**
     * Getter for <code>TICKET_TABLE.PRICE</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public BigInteger getPrice() {
        return (BigInteger) get(4);
    }

    /**
     * Setter for <code>TICKET_TABLE.PURCHASED_BY</code>.
     */
    public void setPurchasedBy(@Nullable String value) {
        set(5, value);
    }

    /**
     * Getter for <code>TICKET_TABLE.PURCHASED_BY</code>.
     */
    @Size(max = 32)
    @Nullable
    public String getPurchasedBy() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TicketTableRecord
     */
    public TicketTableRecord() {
        super(TicketTable.TICKET_TABLE);
    }

    /**
     * Create a detached, initialised TicketTableRecord
     */
    @ConstructorProperties({"id", "routeId", "dateAndTime", "seatNumber", "price", "purchasedBy"})
    public TicketTableRecord(@Nullable Integer id, @NotNull Integer routeId, @NotNull LocalDateTime dateAndTime, @NotNull Integer seatNumber, @NotNull BigInteger price, @Nullable String purchasedBy) {
        super(TicketTable.TICKET_TABLE);

        setId(id);
        setRouteId(routeId);
        setDateAndTime(dateAndTime);
        setSeatNumber(seatNumber);
        setPrice(price);
        setPurchasedBy(purchasedBy);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TicketTableRecord
     */
    public TicketTableRecord(maks.molch.dmitr.core.jooq.tables.pojos.TicketTable value) {
        super(TicketTable.TICKET_TABLE);

        if (value != null) {
            setId(value.getId());
            setRouteId(value.getRouteId());
            setDateAndTime(value.getDateAndTime());
            setSeatNumber(value.getSeatNumber());
            setPrice(value.getPrice());
            setPurchasedBy(value.getPurchasedBy());
            resetChangedOnNotNull();
        }
    }
}
