/*
 * This file is generated by jOOQ.
 */
package maks.molch.dmitr.analytic.jooq;


import maks.molch.dmitr.analytic.jooq.tables.PurchasedTicketsTable;
import maks.molch.dmitr.analytic.jooq.tables.records.PurchasedTicketsTableRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import javax.annotation.processing.Generated;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
        value = {
                "https://www.jooq.org",
                "jOOQ version:3.19.10"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PurchasedTicketsTableRecord> CONSTRAINT_B = Internal.createUniqueKey(PurchasedTicketsTable.PURCHASED_TICKETS_TABLE, DSL.name("CONSTRAINT_B"), new TableField[]{PurchasedTicketsTable.PURCHASED_TICKETS_TABLE.ID}, true);
}
