/*
 * This file is generated by jOOQ.
 */
package maks.molch.dmitr.analytic.jooq;


import maks.molch.dmitr.analytic.jooq.tables.PurchasedTicketsTable;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in the default schema.
 */
@Generated(
        value = {
                "https://www.jooq.org",
                "jOOQ version:3.19.10"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Tables {

    /**
     * The table <code>PURCHASED_TICKETS_TABLE</code>.
     */
    public static final PurchasedTicketsTable PURCHASED_TICKETS_TABLE = PurchasedTicketsTable.PURCHASED_TICKETS_TABLE;
}
