/*
 * This file is generated by jOOQ.
 */
package maks.molch.dmitr.core.jooq.tables;


import maks.molch.dmitr.core.jooq.DefaultSchema;
import maks.molch.dmitr.core.jooq.Keys;
import maks.molch.dmitr.core.jooq.tables.TicketTable.TicketTablePath;
import maks.molch.dmitr.core.jooq.tables.UserTable.UserTablePath;
import maks.molch.dmitr.core.jooq.tables.records.PurchasedTicketsTableRecord;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import javax.annotation.processing.Generated;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "https://www.jooq.org",
                "jOOQ version:3.19.10"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class PurchasedTicketsTable extends TableImpl<PurchasedTicketsTableRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PURCHASED_TICKETS_TABLE</code>
     */
    public static final PurchasedTicketsTable PURCHASED_TICKETS_TABLE = new PurchasedTicketsTable();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<PurchasedTicketsTableRecord> getRecordType() {
        return PurchasedTicketsTableRecord.class;
    }

    /**
     * The column <code>PURCHASED_TICKETS_TABLE.ID</code>.
     */
    public final TableField<PurchasedTicketsTableRecord, Integer> ID = createField(DSL.name("ID"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>PURCHASED_TICKETS_TABLE.USER_LOGIN</code>.
     */
    public final TableField<PurchasedTicketsTableRecord, String> USER_LOGIN = createField(DSL.name("USER_LOGIN"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>PURCHASED_TICKETS_TABLE.TICKET_ID</code>.
     */
    public final TableField<PurchasedTicketsTableRecord, Integer> TICKET_ID = createField(DSL.name("TICKET_ID"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>PURCHASED_TICKETS_TABLE.PURCHASE_DATETIME</code>.
     */
    public final TableField<PurchasedTicketsTableRecord, LocalDateTime> PURCHASE_DATETIME = createField(DSL.name("PURCHASE_DATETIME"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private PurchasedTicketsTable(Name alias, Table<PurchasedTicketsTableRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PurchasedTicketsTable(Name alias, Table<PurchasedTicketsTableRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>PURCHASED_TICKETS_TABLE</code> table reference
     */
    public PurchasedTicketsTable(String alias) {
        this(DSL.name(alias), PURCHASED_TICKETS_TABLE);
    }

    /**
     * Create an aliased <code>PURCHASED_TICKETS_TABLE</code> table reference
     */
    public PurchasedTicketsTable(Name alias) {
        this(alias, PURCHASED_TICKETS_TABLE);
    }

    /**
     * Create a <code>PURCHASED_TICKETS_TABLE</code> table reference
     */
    public PurchasedTicketsTable() {
        this(DSL.name("PURCHASED_TICKETS_TABLE"), null);
    }

    public <O extends Record> PurchasedTicketsTable(Table<O> path, ForeignKey<O, PurchasedTicketsTableRecord> childPath, InverseForeignKey<O, PurchasedTicketsTableRecord> parentPath) {
        super(path, childPath, parentPath, PURCHASED_TICKETS_TABLE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PurchasedTicketsTablePath extends PurchasedTicketsTable implements Path<PurchasedTicketsTableRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PurchasedTicketsTablePath(Table<O> path, ForeignKey<O, PurchasedTicketsTableRecord> childPath, InverseForeignKey<O, PurchasedTicketsTableRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PurchasedTicketsTablePath(Name alias, Table<PurchasedTicketsTableRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PurchasedTicketsTablePath as(String alias) {
            return new PurchasedTicketsTablePath(DSL.name(alias), this);
        }

        @Override
        public PurchasedTicketsTablePath as(Name alias) {
            return new PurchasedTicketsTablePath(alias, this);
        }

        @Override
        public PurchasedTicketsTablePath as(Table<?> alias) {
            return new PurchasedTicketsTablePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public Identity<PurchasedTicketsTableRecord, Integer> getIdentity() {
        return (Identity<PurchasedTicketsTableRecord, Integer>) super.getIdentity();
    }

    @Override
    @NotNull
    public UniqueKey<PurchasedTicketsTableRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_B;
    }

    @Override
    @NotNull
    public List<UniqueKey<PurchasedTicketsTableRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CONSTRAINT_BE0A);
    }

    @Override
    @NotNull
    public List<ForeignKey<PurchasedTicketsTableRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_BE, Keys.CONSTRAINT_BE0);
    }

    private transient UserTablePath _userTable;

    /**
     * Get the implicit join path to the <code>PUBLIC.USER_TABLE</code> table.
     */
    public UserTablePath userTable() {
        if (_userTable == null)
            _userTable = new UserTablePath(this, Keys.CONSTRAINT_BE, null);

        return _userTable;
    }

    private transient TicketTablePath _ticketTable;

    /**
     * Get the implicit join path to the <code>PUBLIC.TICKET_TABLE</code> table.
     */
    public TicketTablePath ticketTable() {
        if (_ticketTable == null)
            _ticketTable = new TicketTablePath(this, Keys.CONSTRAINT_BE0, null);

        return _ticketTable;
    }

    @Override
    @NotNull
    public PurchasedTicketsTable as(String alias) {
        return new PurchasedTicketsTable(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public PurchasedTicketsTable as(Name alias) {
        return new PurchasedTicketsTable(alias, this);
    }

    @Override
    @NotNull
    public PurchasedTicketsTable as(Table<?> alias) {
        return new PurchasedTicketsTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public PurchasedTicketsTable rename(String name) {
        return new PurchasedTicketsTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public PurchasedTicketsTable rename(Name name) {
        return new PurchasedTicketsTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public PurchasedTicketsTable rename(Table<?> name) {
        return new PurchasedTicketsTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public PurchasedTicketsTable where(Condition condition) {
        return new PurchasedTicketsTable(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public PurchasedTicketsTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public PurchasedTicketsTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public PurchasedTicketsTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    @PlainSQL
    public PurchasedTicketsTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    @PlainSQL
    public PurchasedTicketsTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    @PlainSQL
    public PurchasedTicketsTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    @PlainSQL
    public PurchasedTicketsTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public PurchasedTicketsTable whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public PurchasedTicketsTable whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
