/*
 * This file is generated by jOOQ.
 */
package maks.molch.dmitr.core.jooq;


import maks.molch.dmitr.core.jooq.tables.*;
import org.jetbrains.annotations.NotNull;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.processing.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.10"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>CARRIER_TABLE</code>.
     */
    public final CarrierTable CARRIER_TABLE = CarrierTable.CARRIER_TABLE;

    /**
     * The table <code>PURCHASED_TICKETS</code>.
     */
    public final PurchasedTickets PURCHASED_TICKETS = PurchasedTickets.PURCHASED_TICKETS;

    /**
     * The table <code>ROUTE_TABLE</code>.
     */
    public final RouteTable ROUTE_TABLE = RouteTable.ROUTE_TABLE;

    /**
     * The table <code>TICKET_TABLE</code>.
     */
    public final TicketTable TICKET_TABLE = TicketTable.TICKET_TABLE;

    /**
     * The table <code>USER_TABLE</code>.
     */
    public final UserTable USER_TABLE = UserTable.USER_TABLE;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    @NotNull
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    @NotNull
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            CarrierTable.CARRIER_TABLE,
                PurchasedTickets.PURCHASED_TICKETS,
            RouteTable.ROUTE_TABLE,
            TicketTable.TICKET_TABLE,
            UserTable.USER_TABLE
        );
    }
}
