/*
 * This file is generated by jOOQ.
 */
package maks.molch.dmitr.core.jooq;


import javax.annotation.processing.Generated;

import maks.molch.dmitr.core.jooq.tables.CarrierTable;
import maks.molch.dmitr.core.jooq.tables.RouteTable;
import maks.molch.dmitr.core.jooq.tables.TicketTable;
import maks.molch.dmitr.core.jooq.tables.UserTable;
import maks.molch.dmitr.core.jooq.tables.records.CarrierTableRecord;
import maks.molch.dmitr.core.jooq.tables.records.RouteTableRecord;
import maks.molch.dmitr.core.jooq.tables.records.TicketTableRecord;
import maks.molch.dmitr.core.jooq.tables.records.UserTableRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.10"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CarrierTableRecord> CONSTRAINT_3 = Internal.createUniqueKey(CarrierTable.CARRIER_TABLE, DSL.name("CONSTRAINT_3"), new TableField[] { CarrierTable.CARRIER_TABLE.NAME }, true);
    public static final UniqueKey<RouteTableRecord> CONSTRAINT_4 = Internal.createUniqueKey(RouteTable.ROUTE_TABLE, DSL.name("CONSTRAINT_4"), new TableField[] { RouteTable.ROUTE_TABLE.ID }, true);
    public static final UniqueKey<TicketTableRecord> CONSTRAINT_5C = Internal.createUniqueKey(TicketTable.TICKET_TABLE, DSL.name("CONSTRAINT_5C"), new TableField[] { TicketTable.TICKET_TABLE.ROUTE_ID, TicketTable.TICKET_TABLE.DATE_AND_TIME, TicketTable.TICKET_TABLE.SEAT_NUMBER }, true);
    public static final UniqueKey<UserTableRecord> CONSTRAINT_C = Internal.createUniqueKey(UserTable.USER_TABLE, DSL.name("CONSTRAINT_C"), new TableField[] { UserTable.USER_TABLE.LOGIN }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<RouteTableRecord, CarrierTableRecord> CONSTRAINT_4D = Internal.createForeignKey(RouteTable.ROUTE_TABLE, DSL.name("CONSTRAINT_4D"), new TableField[] { RouteTable.ROUTE_TABLE.CARRIER_NAME }, Keys.CONSTRAINT_3, new TableField[] { CarrierTable.CARRIER_TABLE.NAME }, true);
    public static final ForeignKey<TicketTableRecord, RouteTableRecord> CONSTRAINT_5 = Internal.createForeignKey(TicketTable.TICKET_TABLE, DSL.name("CONSTRAINT_5"), new TableField[] { TicketTable.TICKET_TABLE.ROUTE_ID }, Keys.CONSTRAINT_4, new TableField[] { RouteTable.ROUTE_TABLE.ID }, true);
}
