/*
 * This file is generated by jOOQ.
 */
package maks.molch.dmitr.core.jooq;


import maks.molch.dmitr.core.jooq.tables.*;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.10"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>CARRIER_TABLE</code>.
     */
    public static final CarrierTable CARRIER_TABLE = CarrierTable.CARRIER_TABLE;

    /**
     * The table <code>PURCHASED_TICKETS</code>.
     */
    public static final PurchasedTickets PURCHASED_TICKETS = PurchasedTickets.PURCHASED_TICKETS;

    /**
     * The table <code>ROUTE_TABLE</code>.
     */
    public static final RouteTable ROUTE_TABLE = RouteTable.ROUTE_TABLE;

    /**
     * The table <code>TICKET_TABLE</code>.
     */
    public static final TicketTable TICKET_TABLE = TicketTable.TICKET_TABLE;

    /**
     * The table <code>USER_TABLE</code>.
     */
    public static final UserTable USER_TABLE = UserTable.USER_TABLE;
}
