/*
 * This file is generated by jOOQ.
 */
package maks.molch.dmitr.core.jooq.tables;


import java.util.Collection;

import javax.annotation.processing.Generated;

import maks.molch.dmitr.core.jooq.DefaultSchema;
import maks.molch.dmitr.core.jooq.Keys;
import maks.molch.dmitr.core.jooq.tables.RouteTable.RouteTablePath;
import maks.molch.dmitr.core.jooq.tables.records.CarrierTableRecord;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.10"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CarrierTable extends TableImpl<CarrierTableRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CARRIER_TABLE</code>
     */
    public static final CarrierTable CARRIER_TABLE = new CarrierTable();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<CarrierTableRecord> getRecordType() {
        return CarrierTableRecord.class;
    }

    /**
     * The column <code>CARRIER_TABLE.NAME</code>.
     */
    public final TableField<CarrierTableRecord, String> NAME = createField(DSL.name("NAME"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>CARRIER_TABLE.PHONE</code>.
     */
    public final TableField<CarrierTableRecord, String> PHONE = createField(DSL.name("PHONE"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    private CarrierTable(Name alias, Table<CarrierTableRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CarrierTable(Name alias, Table<CarrierTableRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>CARRIER_TABLE</code> table reference
     */
    public CarrierTable(String alias) {
        this(DSL.name(alias), CARRIER_TABLE);
    }

    /**
     * Create an aliased <code>CARRIER_TABLE</code> table reference
     */
    public CarrierTable(Name alias) {
        this(alias, CARRIER_TABLE);
    }

    /**
     * Create a <code>CARRIER_TABLE</code> table reference
     */
    public CarrierTable() {
        this(DSL.name("CARRIER_TABLE"), null);
    }

    public <O extends Record> CarrierTable(Table<O> path, ForeignKey<O, CarrierTableRecord> childPath, InverseForeignKey<O, CarrierTableRecord> parentPath) {
        super(path, childPath, parentPath, CARRIER_TABLE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CarrierTablePath extends CarrierTable implements Path<CarrierTableRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CarrierTablePath(Table<O> path, ForeignKey<O, CarrierTableRecord> childPath, InverseForeignKey<O, CarrierTableRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CarrierTablePath(Name alias, Table<CarrierTableRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CarrierTablePath as(String alias) {
            return new CarrierTablePath(DSL.name(alias), this);
        }

        @Override
        public CarrierTablePath as(Name alias) {
            return new CarrierTablePath(alias, this);
        }

        @Override
        public CarrierTablePath as(Table<?> alias) {
            return new CarrierTablePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public UniqueKey<CarrierTableRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_3;
    }

    private transient RouteTablePath _routeTable;

    /**
     * Get the implicit to-many join path to the <code>PUBLIC.ROUTE_TABLE</code>
     * table
     */
    public RouteTablePath routeTable() {
        if (_routeTable == null)
            _routeTable = new RouteTablePath(this, null, Keys.CONSTRAINT_4D.getInverseKey());

        return _routeTable;
    }

    @Override
    @NotNull
    public CarrierTable as(String alias) {
        return new CarrierTable(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public CarrierTable as(Name alias) {
        return new CarrierTable(alias, this);
    }

    @Override
    @NotNull
    public CarrierTable as(Table<?> alias) {
        return new CarrierTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public CarrierTable rename(String name) {
        return new CarrierTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public CarrierTable rename(Name name) {
        return new CarrierTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public CarrierTable rename(Table<?> name) {
        return new CarrierTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public CarrierTable where(Condition condition) {
        return new CarrierTable(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public CarrierTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public CarrierTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public CarrierTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    @PlainSQL
    public CarrierTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    @PlainSQL
    public CarrierTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    @PlainSQL
    public CarrierTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    @PlainSQL
    public CarrierTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public CarrierTable whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public CarrierTable whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
