/*
 * This file is generated by jOOQ.
 */
package maks.molch.dmitr.core.jooq.tables.pojos;


import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;
import java.io.Serializable;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.10"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CarrierTable implements Serializable {

    private static final long serialVersionUID = 1L;

    private String name;
    private String phone;

    public CarrierTable() {}

    public CarrierTable(CarrierTable value) {
        this.name = value.name;
        this.phone = value.phone;
    }

    @ConstructorProperties({ "name", "phone" })
    public CarrierTable(
        @NotNull String name,
        @NotNull String phone
    ) {
        this.name = name;
        this.phone = phone;
    }

    /**
     * Getter for <code>CARRIER_TABLE.NAME</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 32)
    @NotNull
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>CARRIER_TABLE.NAME</code>.
     */
    public void setName(@NotNull String name) {
        this.name = name;
    }

    /**
     * Getter for <code>CARRIER_TABLE.PHONE</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 20)
    @NotNull
    public String getPhone() {
        return this.phone;
    }

    /**
     * Setter for <code>CARRIER_TABLE.PHONE</code>.
     */
    public void setPhone(@NotNull String phone) {
        this.phone = phone;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CarrierTable other = (CarrierTable) obj;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.phone == null) {
            if (other.phone != null)
                return false;
        }
        else if (!this.phone.equals(other.phone))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.phone == null) ? 0 : this.phone.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CarrierTable (");

        sb.append(name);
        sb.append(", ").append(phone);

        sb.append(")");
        return sb.toString();
    }
}
