/*
 * This file is generated by jOOQ.
 */
package maks.molch.dmitr.core.jooq.tables.pojos;


import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;
import java.io.Serializable;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.10"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RouteTable implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String departure;
    private String arrival;
    private String carrierName;
    private Integer durationInMinutes;
    private Integer seatCount;

    public RouteTable() {}

    public RouteTable(RouteTable value) {
        this.id = value.id;
        this.departure = value.departure;
        this.arrival = value.arrival;
        this.carrierName = value.carrierName;
        this.durationInMinutes = value.durationInMinutes;
        this.seatCount = value.seatCount;
    }

    @ConstructorProperties({ "id", "departure", "arrival", "carrierName", "durationInMinutes", "seatCount" })
    public RouteTable(
        @Nullable Integer id,
        @NotNull String departure,
        @NotNull String arrival,
        @NotNull String carrierName,
        @NotNull Integer durationInMinutes,
        @NotNull Integer seatCount
    ) {
        this.id = id;
        this.departure = departure;
        this.arrival = arrival;
        this.carrierName = carrierName;
        this.durationInMinutes = durationInMinutes;
        this.seatCount = seatCount;
    }

    /**
     * Getter for <code>ROUTE_TABLE.ID</code>.
     */
    @Nullable
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>ROUTE_TABLE.ID</code>.
     */
    public void setId(@Nullable Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>ROUTE_TABLE.DEPARTURE</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 32)
    @NotNull
    public String getDeparture() {
        return this.departure;
    }

    /**
     * Setter for <code>ROUTE_TABLE.DEPARTURE</code>.
     */
    public void setDeparture(@NotNull String departure) {
        this.departure = departure;
    }

    /**
     * Getter for <code>ROUTE_TABLE.ARRIVAL</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 32)
    @NotNull
    public String getArrival() {
        return this.arrival;
    }

    /**
     * Setter for <code>ROUTE_TABLE.ARRIVAL</code>.
     */
    public void setArrival(@NotNull String arrival) {
        this.arrival = arrival;
    }

    /**
     * Getter for <code>ROUTE_TABLE.CARRIER_NAME</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 32)
    @NotNull
    public String getCarrierName() {
        return this.carrierName;
    }

    /**
     * Setter for <code>ROUTE_TABLE.CARRIER_NAME</code>.
     */
    public void setCarrierName(@NotNull String carrierName) {
        this.carrierName = carrierName;
    }

    /**
     * Getter for <code>ROUTE_TABLE.DURATION_IN_MINUTES</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Integer getDurationInMinutes() {
        return this.durationInMinutes;
    }

    /**
     * Setter for <code>ROUTE_TABLE.DURATION_IN_MINUTES</code>.
     */
    public void setDurationInMinutes(@NotNull Integer durationInMinutes) {
        this.durationInMinutes = durationInMinutes;
    }

    /**
     * Getter for <code>ROUTE_TABLE.SEAT_COUNT</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Integer getSeatCount() {
        return this.seatCount;
    }

    /**
     * Setter for <code>ROUTE_TABLE.SEAT_COUNT</code>.
     */
    public void setSeatCount(@NotNull Integer seatCount) {
        this.seatCount = seatCount;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final RouteTable other = (RouteTable) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.departure == null) {
            if (other.departure != null)
                return false;
        }
        else if (!this.departure.equals(other.departure))
            return false;
        if (this.arrival == null) {
            if (other.arrival != null)
                return false;
        }
        else if (!this.arrival.equals(other.arrival))
            return false;
        if (this.carrierName == null) {
            if (other.carrierName != null)
                return false;
        }
        else if (!this.carrierName.equals(other.carrierName))
            return false;
        if (this.durationInMinutes == null) {
            if (other.durationInMinutes != null)
                return false;
        }
        else if (!this.durationInMinutes.equals(other.durationInMinutes))
            return false;
        if (this.seatCount == null) {
            if (other.seatCount != null)
                return false;
        }
        else if (!this.seatCount.equals(other.seatCount))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.departure == null) ? 0 : this.departure.hashCode());
        result = prime * result + ((this.arrival == null) ? 0 : this.arrival.hashCode());
        result = prime * result + ((this.carrierName == null) ? 0 : this.carrierName.hashCode());
        result = prime * result + ((this.durationInMinutes == null) ? 0 : this.durationInMinutes.hashCode());
        result = prime * result + ((this.seatCount == null) ? 0 : this.seatCount.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RouteTable (");

        sb.append(id);
        sb.append(", ").append(departure);
        sb.append(", ").append(arrival);
        sb.append(", ").append(carrierName);
        sb.append(", ").append(durationInMinutes);
        sb.append(", ").append(seatCount);

        sb.append(")");
        return sb.toString();
    }
}
