/*
 * This file is generated by jOOQ.
 */
package maks.molch.dmitr.core.jooq.tables.pojos;


import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;
import java.io.Serializable;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.10"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserTable implements Serializable {

    private static final long serialVersionUID = 1L;

    private String login;
    private String password;
    private String fullName;
    private String role;

    public UserTable() {}

    public UserTable(UserTable value) {
        this.login = value.login;
        this.password = value.password;
        this.fullName = value.fullName;
        this.role = value.role;
    }

    @ConstructorProperties({ "login", "password", "fullName", "role" })
    public UserTable(
        @NotNull String login,
        @NotNull String password,
        @NotNull String fullName,
        @Nullable String role
    ) {
        this.login = login;
        this.password = password;
        this.fullName = fullName;
        this.role = role;
    }

    /**
     * Getter for <code>USER_TABLE.LOGIN</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 32)
    @NotNull
    public String getLogin() {
        return this.login;
    }

    /**
     * Setter for <code>USER_TABLE.LOGIN</code>.
     */
    public void setLogin(@NotNull String login) {
        this.login = login;
    }

    /**
     * Getter for <code>USER_TABLE.PASSWORD</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 1000000000)
    @NotNull
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>USER_TABLE.PASSWORD</code>.
     */
    public void setPassword(@NotNull String password) {
        this.password = password;
    }

    /**
     * Getter for <code>USER_TABLE.FULL_NAME</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 64)
    @NotNull
    public String getFullName() {
        return this.fullName;
    }

    /**
     * Setter for <code>USER_TABLE.FULL_NAME</code>.
     */
    public void setFullName(@NotNull String fullName) {
        this.fullName = fullName;
    }

    /**
     * Getter for <code>USER_TABLE.ROLE</code>.
     */
    @Size(max = 32)
    @Nullable
    public String getRole() {
        return this.role;
    }

    /**
     * Setter for <code>USER_TABLE.ROLE</code>.
     */
    public void setRole(@Nullable String role) {
        this.role = role;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserTable other = (UserTable) obj;
        if (this.login == null) {
            if (other.login != null)
                return false;
        }
        else if (!this.login.equals(other.login))
            return false;
        if (this.password == null) {
            if (other.password != null)
                return false;
        }
        else if (!this.password.equals(other.password))
            return false;
        if (this.fullName == null) {
            if (other.fullName != null)
                return false;
        }
        else if (!this.fullName.equals(other.fullName))
            return false;
        if (this.role == null) {
            if (other.role != null)
                return false;
        }
        else if (!this.role.equals(other.role))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.login == null) ? 0 : this.login.hashCode());
        result = prime * result + ((this.password == null) ? 0 : this.password.hashCode());
        result = prime * result + ((this.fullName == null) ? 0 : this.fullName.hashCode());
        result = prime * result + ((this.role == null) ? 0 : this.role.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserTable (");

        sb.append(login);
        sb.append(", ").append(password);
        sb.append(", ").append(fullName);
        sb.append(", ").append(role);

        sb.append(")");
        return sb.toString();
    }
}
