spring:
  application:
    name: core
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USER}
  liquibase:
    enabled: true
debug: false
logging:
  level:
    org:
      springframework:
        security: ERROR
application:
  jwt:
    privateKey: ${JWT_PRIVATE_KEY}
    publicKey: ${JWT_PUBLIC_KEY}
    expire-time-access-token-in-minutes: 5
    expire-time-refresh-token-in-days: 2