spring:
  application:
    name: core
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USER}
  liquibase:
    enabled: true
debug: false
logging:
  level:
    org:
      springframework:
        security: ERROR
application:
  jwt:
    privateKey: ${JWT_PRIVATE_KEY:MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCcbsW8U+4WPqcG0PBq8vq8syTzoIi0V9RwgVKZimyLP7W2ZOMvaqBzU0a7+t/FK48gWLkKsQ3vChDH26DU1D4iK/1pCPf8LGFZmRe+uf3RmYkqrnNT2LwRT62qvLxg/XQtkxkM2GRJJ0Y5oUfsgA/xCncsdv2Hp/dIXVy01xefFeOKP4b/kyR/3sXjTEwSLIJIT1EosF/WOW2DINSAooAla4yW5PBu8ygPFPrbny5zwyUBqjkxteI/ZUrZXRe1g59Q7/PS9fYrwYlzuxOMdoiJtcqBns9DwqqEj6v84S7GOdXkyzbNM3NJ3apBe+krbiQFmY96GrNy1dPUIS0eVCEHAgMBAAECggEAGHP2Y/CIvKBxko6xrj4qNLoaMh0rkWlTU3zbsRWizweX+5l8q+pSh4SCf5sBRLyA5JEJ5+JyZ6Xepqct1mcRCV1wAO2+egRj+VIFlLJVO2DxQKNBct9j0p7uakyTc+Pat88RMOFYl9jUUOjlqdIA6/BzXZeCHSUD8iNp/PjMf/j4o1riuvTwWLMsjlcIIFed7ptWchCNqAOxXFbZh/kUMFAUQTEKPIPlRhPItELOHA+C65JYaSPu/MTsAgiY1oZgmGKFOxFXzOnbFiTEb7HAXbcR5EOcGGW6C4VobqoCCJUEyipMzucBreSRhkhoXOpCV5Ex2JHEW5Jf7yonoVFTUQKBgQDbVds8bn3C3G82/KkTFp6zb+XzQss0/QN8cPYSnyi450xAuR8l5NCzUQyrznHPUYqlWngvzj9cux4+yCQSoUum7HKIMCODaYvP1wOhFVQ7c7D2D+hQDcrVmcRENNbYz+dF8BUCsdBMg/qwjMqQumqwgiSvclmIBHYpAsIOEjmNcQKBgQC2lRYPnx+E9Pl0Jlt+EWNlD645BET1DtQTR7aWLe1GA8Dy2UE2tzYj4Oc3X42lIZr+S53W+TneuPGz5QbriYL/LtkdYXYhMCUoRquprfe7FqheKa6XZma4z5H4JCOOqPe6/rFObYflURghDgSHwAaUtzudbY6X/Mr1G/Yo9/a59wKBgFqUXWLampMzp7ZEp6pbaBTgfE124yax6pOkrurH0fByjPoZuXRTx6CWMy5spnGg0ioxb3sGqQIpwHba/pK3C+AWu8HkZ3Yoy3V87WHDxjJ7N7SWozEUURTfWL92Ntf5HCC04mhneIdw5cGtkyYr5k2YoX/XMIRMm2OaYPugqSXxAoGAAeCyo2J9jn5+ekVSt48yOH3aytdSZjrKz4/zPsQmJowvVdAKLafgtKnBdv5SlJot3+OjMezKPZIlWjZGxfFaGYm/zd+MuXanSyy+4zXY0GHBRYakNwZklA3+cFDe1L7EHXY1GJtjxGX7G4vrXAILj0f7IvlXeBSveanZ9D3oma0CgYEAxChb0OMN3AQgL8cgx/5urGz/Q6/sAtIa6jCgBf6XeLUnJUpZiHpDbGS5fIBTM3Vm/F6uiArY6yq/bEVEw88OtsFLWmcFcj9OjjjAlxGr+N4flXvuFXLJGOxsh9/kh9z/8UDWS5MhymmWBY9R5S4aL3Js+Zm31jRWtKYURftKs/w=}
    publicKey: ${JWT_PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnG7FvFPuFj6nBtDwavL6vLMk86CItFfUcIFSmYpsiz+1tmTjL2qgc1NGu/rfxSuPIFi5CrEN7woQx9ug1NQ+Iiv9aQj3/CxhWZkXvrn90ZmJKq5zU9i8EU+tqry8YP10LZMZDNhkSSdGOaFH7IAP8Qp3LHb9h6f3SF1ctNcXnxXjij+G/5Mkf97F40xMEiyCSE9RKLBf1jltgyDUgKKAJWuMluTwbvMoDxT6258uc8MlAao5MbXiP2VK2V0XtYOfUO/z0vX2K8GJc7sTjHaIibXKgZ7PQ8KqhI+r/OEuxjnV5Ms2zTNzSd2qQXvpK24kBZmPehqzctXT1CEtHlQhBwIDAQAB}
    expire-time-access-token-in-minutes: 5
    expire-time-refresh-token-in-days: 2